title: M4 Metal Prefill Engine
description: Hardware-Saturated Prefill Inference on Apple M4 Silicon
theme: jekyll-theme-cayman
author: Mohammed Hossam
url: https://mohamedhossammohamed.github.io
baseurl: /m4-prefill-engine
twitter_username: MohamedHz72007
github_username: mohamedhossammohamed
